FROM node:24.5.0-slim AS builder

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

WORKDIR /home/aiagent

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json next.config.mjs next-env.d.ts postcss.config.js drizzle.config.ts tailwind.config.ts ./
COPY src ./src
COPY public ./public
COPY drizzle ./drizzle

RUN mkdir -p /home/aiagent/data
COPY data/documents ./data/documents
RUN npm run build

FROM node:24.5.0-slim

WORKDIR /home/aiagent

COPY --from=builder /home/aiagent/public ./public
COPY --from=builder /home/aiagent/.next/static ./public/_next/static

COPY --from=builder /home/aiagent/.next/standalone ./
COPY --from=builder /home/aiagent/node_modules/@firecrawl ./node_modules/@firecrawl
COPY --from=builder /home/aiagent/data ./data
COPY drizzle ./drizzle

EXPOSE 3000

CMD ["node", "server.js"]
